FizzBuzz/FizzBuzz/Models/FizzBuzzModel.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace FizzBuzz.Models
{
    public class FizzBuzzModel
    {
        [Range(1, 1000, ErrorMessage = "Error: must be between 1 and 1000")]
        public int userInput { get; set; }
        public ArrayList fbValues { get; set; }


        public void calcFizzBuzz()
        {
            ArrayList fb = new ArrayList();

            for (int i = 1; i < (userInput + 1); i++)
            {
                if ((i % 3) == 0 && (i % 5) == 0)
                {
                    fb.Add("fizz buzz");
                }
                else if (i % 3 == 0)
                {
                    fb.Add("fizz");
                }
                else if (i % 5 == 0)
                {
                    fb.Add("buzz");
                }
                else
                {
                    fb.Add(i);
                }
                                
            }

            fbValues = fb;
        }


        
    }
}

FizzBuzz/FizzBuzz/Controllers/FizzBuzzController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FizzBuzz.Models;

namespace FizzBuzz.Controllers
{
    public class FizzBuzzController : Controller
    {
        // First time page loads
        public ActionResult Index()
        {
            // Clears model validation so no errors appear when page first loaded
            ModelState.Remove("userInput");
            return View("Index");
        }

        // After form is submitted, run full validation
        [HttpPost]
        public ActionResult Index(FizzBuzzModel fb)
        {
            if(!ModelState.IsValid)
            {
                return View("Index");
            }

            fb.calcFizzBuzz();
            ViewBag.FB = fb.fbValues;

            return View("Index");
        }
    }
}

FizzBuzz/FizzBuzz/Views/FizzBuzz/Index.cshtml
@model FizzBuzz.Models.FizzBuzzModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 


        Enter Fizz Buzz length:

        @using (Html.BeginForm("Index", "FizzBuzz"))
        {
            @Html.TextBoxFor(model => model.userInput)
            <input type="submit" value="Run Fizz Buzz" />
            @Html.ValidationMessageFor(model => model.userInput)
        }

        <!-- Only run if FizzBuzz values exist-->
        @if (ViewBag.FB != null)
        {
            foreach (var value in ViewBag.FB)
            {
                if(value.ToString() == "fizz")
                {
                    if (DateTime.Now.DayOfWeek == DayOfWeek.Wednesday)
                    {
                        <span style="color:blue">wizz</span><br />
                    }
                    else
                    {
                        <span style="color:blue">fizz</span> <br />
                    }
                }
                else if(value.ToString() == "buzz")
                {
                    if (DateTime.Now.DayOfWeek == DayOfWeek.Wednesday)
                    {
                        <span style="color:green">wuzz</span> <br />
                    }
                    else
                    {
                        <span style="color:green">buzz</span><br />
                    }
                }
                else if (value.ToString() == "fizz buzz")
                {
                    if (DateTime.Now.DayOfWeek == DayOfWeek.Wednesday)
                    {
                        <span style="color:blue">wizz</span>
                        <span style="color:green"> wuzz</span> <br />
                    }
                    else
                    {
                        <span style="color:blue">fizz</span>
                        <span style="color:green"> buzz</span> <br />
                    }
                }
                else
                {
                    @value <br />
                }


            }
        }

    </div>
</body>
</html>

FizzBuzz/FizzBuzz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Fizz Buzz</title>
    @Styles.Render("~/Content/fbCSS.css")
</head>
<body>
    <div> 
        <div class="header">
            <h1>Fizz Buzz</h1>
        </div>

        <div class="main">
            @RenderBody()
        </div>
    </div>
</body>
</html>